### 添加请求
POST http://localhost:8181/sysHall
Content-Type: application/json

{
  "cinemaId": 7,
  "hallId": 3,
  "hallName": "3号厅",
  "hallCategoryId": 2,
  "rowNums": 15,
  "rowStart": "1",
  "seatNumsRow": 20,
  "seatNums": 300,
  "seatState": "[{\"1\": [2,2,0,0,0]},{\"2\": [0,0,0,0,0]},{\"3\": [0,0,0,0,0]}]",
  "hallState": false
}

### 查询所有
GET http://localhost:8181/sysHall?hallState=1
Accept: application/json

### 查询一个
GET http://localhost:8181/sysHall/1/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysHall
Content-Type: application/json

{
  "cinemaId": 7,
  "hallId": 2,
  "hallName": "5号厅",
  "hallCategoryId": 5,
  "rowStart": "A",
  "rowNums": 15,
  "seatNums": 300,
  "hallState": false
}

### 删除
POST http://localhost:8181/sysHall/delete
Content-Type: application/json

[
  {
    "cinemaId": 7,
    "hallId": 2
  }
]
