### 添加请求
POST http://localhost:8080/sysMovieAge
Content-Type: application/json

{"movieAgeName":""}


### 查询所有
GET http://localhost:8080/sysMovieAge
Accept: application/json

### 查询一个
GET http://localhost:8080/sysMovieAge/15
Accept: application/json

### 修改
PUT http://localhost:8080/sysMovieAge
Content-Type: application/json

{"movieAgeId":18,"movieAgeName":"修改测试"}

### 删除
DELETE http://localhost:8080/sysMovieAge/18
