### 添加请求
POST http://localhost:8080/sysMovieAge
Content-Type: application/x-www-form-urlencoded

movieAgeName=测试添加


### 查询所有
GET http://localhost:8080/sysMovieAge
Accept: application/json

### 查询一个
GET http://localhost:8080/sysMovieAge/4
Accept: application/json

### 修改
PUT http://localhost:8080/sysMovieAge
Content-Type: application/x-www-form-urlencoded

movieAgeId=20&movieAgeName=修改测试1

### 删除
DELETE http://localhost:8080/sysMovieAge/20
